

### GET
GET http://localhost:8000/productos/

### POST
POST http://localhost:8000/productos/
Content-Type:65 application/json
{
    "NOMBRES": "JULIO",
    "APELLIDOS": "PEÑA BERDUGO",
    "DOCUMENTO": "1002740965",
    "EMAIL": "jlopez@example.com"
}

### Delete
DELETE http://localhost:8000/productos/


###  -----  CATEGORIAS  -----

## GET
GET  http://localhost:8000/categorias/

### Crear una nueva categoría
POST http://localhost:8000/categorias/
Content-Type: application/json

{
  "tipoProd": "Tipo Ejemplo",
  "tipoDescripcion": "Cualquiera",
  "estado": 1,
  "fecha": "2024-03-02T12:00:00Z"
}

### Actualizar una categoría por ID 
PUT http://localhost:8000/categorias/6
Content-Type: application/json

{
  "tipoProd": "Tipo X",
  "tipoDescripcion": "Cualquier otro",
  "estado": 1,
  "fecha": "2022-05-02T12:00:00Z"
}

### Eliminar una categoría por ID
DELETE http://localhost:8000/categorias/6