
###  -----  PRODUCTOS  -----

### GET
GET http://localhost:8000/productos/

### POST
POST http://localhost:8000/productos/
Content-Type:65 application/json
{
    "NOMBRES": "JULIO",
    "APELLIDOS": "PEÑA BERDUGO",
    "DOCUMENTO": "1002740965",
    "EMAIL": "jlopez@example.com"
}


###  -----  CATEGORIAS  -----

## GET
GET  http://localhost:8000/categorias/